### ISSUE TITLE
About Fig3 in paper

### ISSUE THREAD

**Issue by chenzhuer** [helme/ecg_ptbxl_benchmarking#11]
Hi~ Thank you for your very helpful work！
I want to know the exact values in Fig. 3: Effect of transfer learning from PTB-XL to ICBEB2018 upon varying the size of the ICBEB2018 train- ing set.
Thx！

**Comment by helme** [comment]
Hi @chenzhuer, sorry for my late reply,

I attached two csv-files, one for each method (finetuned vs. from scratch). Each csv has 4 columns: folds, point, lower, upper. I hope this helps you!
[raw_macro_auc_finetuned.csv](https://github.com/helme/ecg_ptbxl_benchmarking/files/6343902/raw_macro_auc_finetuned.csv)
[raw_macro_auc_from_scratch.csv](https://github.com/helme/ecg_ptbxl_benchmarking/files/6343904/raw_macro_auc_from_scratch.csv)
