### ISSUE TITLE
Likelihood not considered in multi-label classification

### ISSUE THREAD

**Issue by kcdharmaua** [helme/ecg_ptbxl_benchmarking#2]
Hi,
In you code I saw that even if the scp_codes is like this {'Norm':100.0, 'LVOLT': 0.0, 'SR':0.0}, you have taken all these labels as the correct ones for 71 way multi-label classification. Is that correct? According to what I understand the above dictionary is label:likelihood. So should not the 'SR' and 'LVOLT' be removed from the multi-label as they have likelihoods of zero? Correct me if I am wrong. Thank you.

**Comment by nstrodt** [comment]
Hi kcdharmaua,
yes this correct. For the form and rhythm statements there are no likelihoods available and the corresponding values in the dictionaries are always set to zero- see the description of the PTB-XL dataset.
Best
Nils
