### ISSUE TITLE
Hello,I want to ask trhat you only use preprocess and good models to do classfication?

### ISSUE THREAD

**Issue by PGCJ** [helme/ecg_ptbxl_benchmarking#21]

**Comment by PGCJ** [comment]
And,Did you compare multiple labels with single labels in terms of evaluating the data?

**Comment by helme** [comment]
sorry, I don't get your problem and I think it's not an issue with this repository here.

**Comment by PGCJ** [comment]
> sorry, I don't get your problem and I think it's not an issue with this repository here.

I am resolving it , thank you very much
