### ISSUE TITLE
Bug in  code/models/xresnet1d.py

### ISSUE THREAD

**Issue by v3551G** [helme/ecg_ptbxl_benchmarking#26]
This is a really interesting piece of work, and I think it will have a positive impact on the field.

I found that the implementation of some functions such as weight_norm, spectral_norm, InstanceNorm, SEModule, and SimpleSelfAttention in the xresnet1d.py file  is missing. Can you provide a complete file??

Thank you sincerely.

**Comment by helme** [comment]
#27
