### ISSUE TITLE
Bug in xresnet1d.py

### ISSUE THREAD

**Issue by v3551G** [helme/ecg_ptbxl_benchmarking#27]
This is a really interesting piece of work, and I think it will have a positive impact on the field.

I found that the implementation of some functions such as weight_norm, spectral_norm, InstanceNorm, SEModule, and SimpleSelfAttention in the xresnet1d.py file  is missing. Can you provide a complete file??

Thank you sincerely.

**Comment by Skorik99** [comment]
Hello! A similar issue was raised here #18. In short, you can update the fastai version to 2. and import these functions from the modules:
```
from fastai.layers import LinBnDrop, AdaptiveConcatPool1d, SEModule, SimpleSelfAttention, InstanceNorm
```
You can find `weighted_norm` and `spectral_norm`  in original implementation of `ConvLayer` https://github.com/fastai/fastai/blob/master/fastai/layers.py#L239. You can see that they are simply imported from `torch` like
```
from torch.nn.utils import weight_norm, spectral_norm
```

**Comment by PGCJ** [comment]
hello firend, it is working now? I found that the code misses a lot of packets, i do not know how to solve and run it. Could you teach me?

**Comment by helme** [comment]
@Skorik99 thank yo uvery much for pointing this out! 
@v3551G does this resolve your issue?
@PGCJ you need to follow the README in order to install a virtual environment using conda.
