### ISSUE TITLE
Extraction of representations from hidden layers

### ISSUE THREAD

**Issue by ansuini** [helme/ecg_ptbxl_benchmarking#3]
Dear Team,

thanks for this fantastic work, I think it will be of great value for the scientific community.

I kindly ask you  to add the functionality to extract representations (i.e. the activations
of the hidden units) from a specified hidden layer of one or some of the models.

To be more specific, I think a single representation of 2.5 seconds long 12-lead ECGs would be the best option (as pointed out in our private communication).

Typically the most interesting layers are those close to the output e.g. the last or second last hidden layer, but it could be also interesting to extract activations from a generic layer, in order to make sense of how networks "solve" this problem.

Thank you again and

Best Regards!

Alessio Ansuini

**Comment by nstrodt** [comment]
Dear Alessio,
thank you for your interest in our work. You are touching an important issue in how to extract discriminative representation from a given trained model. At the moment, we don't have any plans to extend the code in this repository in this direction but it should be pretty straightforward for you to do this yourself. The easiest way to implement this would be to make use of `torch.nn.Module.register_forward_hook` to attach a hook to the layer you are interested in that stores the output of this particular layer away. Looking forward to future progress in this direction.

Best
Nils

**Comment by ansuini** [comment]
Dear Nils,
                thank you very much for your reply and your suggestion.
I will post on this subject again, when I will have made progress in this direction.

All the Best,
Alessio
