### ISSUE TITLE
"from fastai.core import * " is missing!

### ISSUE THREAD

**Issue by PGCJ** [helme/ecg_ptbxl_benchmarking#30]
Using lib "fastai" is difficult to repeat. How can I run this code?

**Comment by helme** [comment]
please read the [README](https://github.com/helme/ecg_ptbxl_benchmarking?tab=readme-ov-file#install-dependencies) about installing dependencies into your conda environment (where `fastai` is included).

**Comment by PGCJ** [comment]
> please read the [README](https://github.com/helme/ecg_ptbxl_benchmarking?tab=readme-ov-file#install-dependencies) about installing dependencies into your conda environment (where `fastai` is included).

thanks , it was woking. The fastai's version is updating now, needing to watch the README's descirption
