### ISSUE TITLE
Pytorch Version

### ISSUE THREAD

**Issue by chenzhuer** [helme/ecg_ptbxl_benchmarking#9]
Hi， thanks for your solid and comprehensive work！
I'm a little confused about Fastai， could u please release pytorch version of such models especially the Top-Performing xresnet101-1d？
Thanks a lot!

**Comment by nstrodt** [comment]
All models are just plain Pytorch models (if you want you can entirely remove the few fastai utilities being used from the model definitions by copying a few lines from the corresponding fastai source). Pretrained models are available from our [datacloud](https://datacloud.hhi.fraunhofer.de/s/gLkjQL94d7FXBbS).
